cat('############    -------------  General script for FACS analysis plots  -------------    ############\n')
cat("\n")
# Version: 1
# Subversion: 0
# Sub-subversion: 0
# Updates.

#### Libraries ####
cat('Importing libraries...\n')
library(optparse)
library(ggplot2)
library(stringr)
library(tidyverse)
library(pals)
#source('/home/vkeiner/handy_functions/')
cat('Libraries imported!\n')

#### Arguments ####
cat("Arguments \n")

# Declaring arguments to parse from command line ----------------------->
option.list <- list(
  make_option(opt_str="--inputcsv", type="character", default=NULL, dest="inputcsv", help="Absolute path to a , - separated csv generated by flowjo. First colum = tube name where experimental conditions are divided by _ (e.g. Donor1_timepoint1_with-stimulation) and the rest of the columns are numeric statistics"),
  make_option(opt_str="--metaElements", type="character", default=NULL, dest="metaElements", help="One string with names separated by _ for metadata elemets separated by _ in the first column of the input csv. This string is split and matched to the stringsplit results of the metadata column. Add EXCLUDE to not consider one colum (e.g. running number)")
)

# Getting arguments from command line and setting their values to their respective variable names.
opt.parser <- OptionParser(option_list=option.list)
opt <- parse_args(opt.parser)


this.color.scale <- pals::kelly(n = 22)
this.color.scale[1] <- "grey50"
# Presenting parameters ------------------------------------------------>
cat('\n\n')

#### Functions ####
cat("Functions \n")

gen_facs_plotter <- function(csv.in.path, meta.elements){

  #reading in data
  df <- read.csv(file = csv.in.path, header = F, sep = ",")
  
  #get names of df right
  for(i in 2:ncol(df)){
    splitname <- stringr::str_split(df[1,i], "/", simplify = T)
    splitname <- gsub("\\+", "pos", splitname)
    splitname <- gsub("\\-", "neg", splitname)
    splitname <- gsub("\\| ", "", splitname)
    splitname <- gsub("\\(%\\)", "perc", splitname)
    splitname <- gsub("\\.", "", splitname)
    splitname <- gsub(" ", "_", splitname)
    df[1,i] <- paste0(splitname[(length(splitname)-1):length(splitname)], collapse = "_")  #removing the single cell population annotations
  } 
  
  df[1,1] <- "tube"
  names(df) <- df[1,]
  df <- df[-1,]
  
  #exclude any column with na in there names
  df <- df[,!str_detect(names(df), "NA")]
  
  print(df)

  #clean table
  df[,1] <- as.character(df[,1])
  df[,1] <- gsub(".fcs", "", df[,1])
  df <- df[-c((nrow(df)-1):nrow(df)),!stringr::str_detect(names(df), pattern = "X_\\d")] #remove last two rows with mean and sd information as well as columns with names like X.1 which are usually empty columns
  for(i in 2:ncol(df)){
    df[,i] <- as.numeric(as.character(df[,i])) #make all other columns numeric
  } 
  
  #get and order metadata info from first column
  metadf  <- as.data.frame(stringr::str_split(df[,1], "_", simplify = T))
  meta.elements.split <- stringr::str_split(meta.elements, "_", simplify = T)[1,] #add names as in input
  names(metadf) <- meta.elements.split

  #remove excluded column
  metadf <- metadf[,!stringr::str_detect(names(metadf), pattern = "EXCLUDE")]
  metadf <- metadf[,!stringr::str_detect(names(metadf), pattern = "exclude")]
  
  #check columns and see which ones to group by
  to_del <- c()
  for(i in 1:ncol(metadf)){
    if(length(unique(metadf[,i])) == 1){to_del <- c(to_del, i)  #remove columns with only one unique entry to avoid grouping on these
    } else {
        print(i)
      metadf[,i] <- ordered(as.factor(metadf[,i]), levels = unique(metadf[,i]))}} #order column entries
  if(length(to_del > 0)) metadf <- metadf[-to_del]
  #join back with dataframe
  df <- cbind(metadf, df[,-1])  
  
  #open pdf
  pdf.path <- gsub("\\.csv", "_plots.pdf", csv.in.path)
  pdf(file = pdf.path, width = 10, height = 6, onefile = T)
  
  #grouping and plotting loops
  if(ncol(metadf) == 1){ #one column to plot e.g. only timecourse
    
    for(j in 2:ncol(df)){ #looping across metrics
    
    plot_out <- ggplot(data = df, aes(x = df[,1], y = df[,j], fill = "grey40"), col = "black") + geom_bar(show.legend = T, alpha = 1, stat = "identity", width = 0.6) + theme(panel.background = element_blank(),axis.text.x = element_text(angle = 50,vjust = 1, hjust=1, size = 16),axis.text.y = element_text(size = 16), axis.line.x = element_line(size = 1),axis.line.y = element_line(size = 1), axis.ticks = element_line(size = 1), axis.ticks.length = unit(0.3, "cm"), text = element_text(size=16), legend.position = "top",legend.direction = "horizontal", plot.subtitle = element_text(size = 16), plot.margin = margin(0,10,0, 10, unit = "pt")) + labs(title = "", x = names(df)[1], y = names(df)[j], subtitle = "", fill = "") + scale_fill_manual(values = "grey40") + scale_y_continuous(expand = c(0,0))
  
    print(plot_out)
    }
  } else if(ncol(metadf) == 2){
    
    #First combination
    for(j in 3:ncol(df)){ #looping across metrics
      
      plot_out <- ggplot(data = df, aes(x = df[,1], y = df[,j], fill = df[,2]), col = "black") + geom_bar(show.legend = T, alpha = 1, stat = "identity", position = "dodge", width = 0.6) + theme(panel.background = element_blank(),axis.text.x = element_text(angle = 50,vjust = 1, hjust=1, size = 16),axis.text.y = element_text(size = 16), axis.line.x = element_line(size = 1),axis.line.y = element_line(size = 1), axis.ticks = element_line(size = 1), axis.ticks.length = unit(0.3, "cm"), text = element_text(size=16), legend.position = "top",legend.direction = "horizontal", plot.subtitle = element_text(size = 16), plot.margin = margin(0,10,0, 10, unit = "pt")) + labs(title = "", x = names(df)[1], y = names(df)[j], subtitle = "", fill = names(df)[2]) + scale_fill_manual(values = this.color.scale[1:length(unique(df[,2]))]) + scale_y_continuous(expand = c(0,0))
      
      print(plot_out)
    }
    
    #second combination
    for(j in 3:ncol(df)){ #looping across metrics
      
      plot_out <- ggplot(data = df, aes(x = df[,2], y = df[,j], fill = df[,1]), col = "black") + geom_bar(show.legend = T, alpha = 1, stat = "identity", position = "dodge", width = 0.6) + theme(panel.background = element_blank(),axis.text.x = element_text(angle = 50,vjust = 1, hjust=1, size = 16),axis.text.y = element_text(size = 16), axis.line.x = element_line(size = 1),axis.line.y = element_line(size = 1), axis.ticks = element_line(size = 1), axis.ticks.length = unit(0.3, "cm"), text = element_text(size=16), legend.position = "top",legend.direction = "horizontal", plot.subtitle = element_text(size = 16), plot.margin = margin(0,10,0, 10, unit = "pt")) + labs(title = "", x = names(df)[1], y = names(df)[j], subtitle = "", fill = names(df)[1]) + scale_fill_manual(values = this.color.scale[1:length(unique(df[,1]))]) + scale_y_continuous(expand = c(0,0))
      
      print(plot_out)
    }
  } else if(ncol(metadf) == 3){
    
    #First combination
    for(j in 4:ncol(df)){ #looping across metrics
      
      plot_out <- ggplot(data = df, aes(x = df[,1], y = df[,j], fill = df[,2]), col = "black") + geom_bar(show.legend = T, alpha = 1, stat = "identity", position = "dodge", width = 0.6) + theme(panel.background = element_blank(),axis.text.x = element_text(angle = 50,vjust = 1, hjust=1, size = 16),axis.text.y = element_text(size = 16), axis.line.x = element_line(size = 1),axis.line.y = element_line(size = 1), axis.ticks = element_line(size = 1), axis.ticks.length = unit(0.3, "cm"), text = element_text(size=16), legend.position = "top",legend.direction = "horizontal", plot.subtitle = element_text(size = 16), plot.margin = margin(0,10,0, 10, unit = "pt")) + labs(title = "", x = names(df)[1], y = names(df)[j], subtitle = paste0("Split by: ", names(df)[3]), fill = names(df)[2]) + scale_fill_manual(values = this.color.scale[1:length(unique(df[,2]))]) + scale_y_continuous(expand = c(0,0)) + facet_wrap(~df[,3], scales = "fixed")
      
      print(plot_out)
    }
    
    #second combination
    for(j in 4:ncol(df)){ #looping across metrics
      
      plot_out <- ggplot(data = df, aes(x = df[,2], y = df[,j], fill = df[,3]), col = "black") + geom_bar(show.legend = T, alpha = 1, stat = "identity", position = "dodge", width = 0.6) + theme(panel.background = element_blank(),axis.text.x = element_text(angle = 50,vjust = 1, hjust=1, size = 16),axis.text.y = element_text(size = 16), axis.line.x = element_line(size = 1),axis.line.y = element_line(size = 1), axis.ticks = element_line(size = 1), axis.ticks.length = unit(0.3, "cm"), text = element_text(size=16), legend.position = "top",legend.direction = "horizontal", plot.subtitle = element_text(size = 16), plot.margin = margin(0,10,0, 10, unit = "pt")) + labs(title = "", x = names(df)[1], y = names(df)[j], subtitle = paste0("Split by: ", names(df)[1]), fill = names(df)[3]) + scale_fill_manual(values = this.color.scale[1:length(unique(df[,3]))]) + scale_y_continuous(expand = c(0,0)) + facet_wrap(~df[,1], scales = "fixed")
      
      print(plot_out)
    }
    
    #third combination
    for(j in 4:ncol(df)){ #looping across metrics
      
      plot_out <- ggplot(data = df, aes(x = df[,3], y = df[,j], fill = df[,1]), col = "black") + geom_bar(show.legend = T, alpha = 1, stat = "identity", position = "dodge", width = 0.6) + theme(panel.background = element_blank(),axis.text.x = element_text(angle = 50,vjust = 1, hjust=1, size = 16),axis.text.y = element_text(size = 16), axis.line.x = element_line(size = 1),axis.line.y = element_line(size = 1), axis.ticks = element_line(size = 1), axis.ticks.length = unit(0.3, "cm"), text = element_text(size=16), legend.position = "top",legend.direction = "horizontal", plot.subtitle = element_text(size = 16), plot.margin = margin(0,10,0, 10, unit = "pt")) + labs(title = "", x = names(df)[1], y = names(df)[j], subtitle = paste0("Split by: ", names(df)[2]), fill = names(df)[1]) + scale_fill_manual(values = this.color.scale[1:length(unique(df[,1]))]) + scale_y_continuous(expand = c(0,0)) + facet_wrap(~df[,2], scales = "fixed")
      
      print(plot_out)
    }
  }
  
  #print datatable for reference
  print(df)
  
  #close pdf
  dev.off()
  
  csv.path <- gsub("\\.csv", "_formatted.csv", csv.in.path)
  write.csv(df, file = csv.path)
  
}

#a <- gen_facs_plotter(csv.in.path = "/Volumes/VD-Vijay/LAB/Victor/DICE_R24/Experiments/exp_005_VK_withBS_110121_NKstim_repeat_r1/VK_005_110521_NKstim/exp005_raw_results-1.csv", meta.elements = "Prestimulation_EXCLUDE_timepoint_hIgG-stim")

#### VDJ_GEX_matrix run ####
cat('\n\n Plotting \n')

gen_facs_plotter(csv.in.path = opt$inputcsv, meta.elements = opt$metaElements)

cat('\n\n')
#### Save ####
cat('Done \n')

cat('\n\nSession info:')
sessionInfo()

cat('\n\nProgram finished.\n')
